import "./About.css";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
import ProfileCard from "../../components/ProfileCard";
import { teamInfo } from "../../components/MemberInfo";
import "../../App.css";

function About() {
  const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 3000 },
      items: 5,
    },
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };

  return (
    <>
      <section id="about-container" className="section-container">
        <h2 className="page-heading">Our Objective</h2>
        <p className="about-text">
          Our objective with this project was to faciliate the movie watching
          process for users. We wanted to create a website where users could
          create their own personalized list of movies and give the movies
          they've watched ratings. Sometimes, we're not sure what to watch and
          we just need some recommendations to help us out. That's where
          Google's AI tool 'Gemini' comes in. Our goal was to use the power of
          Gemini to bring users movie recommendations based on a specific genre
          and their own movie list. Since Gemini will output something
          relatively new everytime, users will always have many options in terms
          of what to watch next, and even if they don't watch it right away,
          they can still add it to the "Watching Soon" section of their list.
          This way users have an organized list to save movies for watching
          later or for saving an already watched movie with a rating so they
          remember what movies they enjoyed and which ones they didn't. This
          idea helps users maintain a list that disregards what platform holds
          rights to that movie so they don't have to go searching all of their
          streaming apps looking for what film to see next.
        </p>
        <h2 className="page-heading">Our Features</h2>
        <ul className="features">
          <li className="about-text">
            Users can browse trending and popular movies in the database from
            the TMDB API. Movie names, titles, or even just keywords can be
            entered into the search bar to find a specific movie or movies with
            similar names.
          </li>
          <li className="about-text">
            Users can click on a movie to reveal movie metadata including the
            movie title, overview, genres, release date, etc. On this same
            screen users can give movies rating, but only if the movie is in
            their list and set to "Watched". Ratings range from 1-5 in the form
            of stars.
          </li>
          <li className="about-text">
            Users can save movies to their list, more specifically either their
            "Watched" list or their "Watching Soon" list. Users will then get
            recommendations based on the movies in their list. This can be seen
            in the list page of our website. Recommendations are generated by
            Gemini.
          </li>
        </ul>
        <h2 className="page-heading">The Team</h2>
        <Carousel responsive={responsive}>
          {teamInfo.map((val, key) => (
            <ProfileCard key={`member-${key}`} member={val} />
          ))}
        </Carousel>
      </section>
    </>
  );
}

export default About;
